# Generated by Django 5.2.4 on 2025-09-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_documentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinflow',
            name='serial_lot_number',
        ),
        migrations.RemoveField(
            model_name='productoutflow',
            name='serial_numbers',
        ),
        migrations.CreateModel(
            name='ProductSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('dispatched', 'Dispatched'), ('returned', 'Returned')], default='in_stock', max_length=20)),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='product_documentation.productinflow')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddField(
            model_name='productoutflow',
            name='serial_numbers',
            field=models.ManyToManyField(related_name='outflows', to='product_documentation.productserialnumber'),
        ),
    ]
