# Generated by Django 5.2.4 on 2025-07-09 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalytics',
            name='item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockanalytics',
            name='obsolescence_risk',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockanalytics',
            name='turnover_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_analytics', to=settings.AUTH_USER_MODEL),
        ),
    ]
