# Generated by Django 5.2.4 on 2025-07-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions_and_more'),
        ('analytics', '0002_alter_stockanalytics_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelltime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='eoqreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
