# Generated by Django 5.2.4 on 2025-09-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_documentation', '0002_remove_productinflow_serial_lot_number_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='item',
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='serial_number',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='product_documentation.productserialnumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('dispatched', 'Dispatched')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
