# Generated by Django 5.2.4 on 2025-09-16 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_equipment_created_at_equipment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
