# Generated by Django 5.2.4 on 2025-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('md', 'Managing Director'), ('admin', 'Admin')], default='staff', max_length=30),
        ),
    ]
