# Generated by Django 5.2.4 on 2025-08-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True)),
                ('min_role', models.CharField(choices=[('staff', 'Staff'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('md', 'Managing Director'), ('admin', 'Admin')], default='staff', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('min_role', models.CharField(choices=[('staff', 'Staff'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('md', 'Managing Director'), ('admin', 'Admin')], default='staff', max_length=30)),
            ],
        ),
    ]
