# Generated by Django 5.2.4 on 2025-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='custom_fields',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.CharField(max_length=255),
        ),
    ]
