# Generated by Django 5.2.4 on 2025-07-14 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_batch_alter_item_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2025, 7, 14)),
            preserve_default=False,
        ),
    ]
