# Generated by Django 5.2.4 on 2025-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebin',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
