# Generated by Django 5.2.4 on 2025-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_storagebin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebin',
            name='rack',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagebin',
            name='row',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagebin',
            name='shelf',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
