# Generated by Django 5.2.4 on 2025-09-11 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_name_item_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('item_added', 'Item Added'), ('item_removed', 'Item Removed')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='storage_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagebin'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='rack',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='row',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='storagebin',
            unique_together={('row', 'rack')},
        ),
        migrations.AddIndex(
            model_name='storagebin',
            index=models.Index(fields=['row', 'rack'], name='inventory_s_row_ac03b3_idx'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='storage_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.storagebin'),
        ),
    ]
