# Generated by Django 5.2.4 on 2025-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_locationevent_stockrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationevent',
            name='uantity',
            field=models.IntegerField(default=1),
        ),
    ]
