# Generated by Django 5.2.4 on 2025-09-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_locationevent_uantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationevent',
            old_name='uantity',
            new_name='quantity',
        ),
    ]
