# Generated by Django 5.2.4 on 2025-09-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecord',
            name='category',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='storage_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_records', to='inventory.storagebin'),
        ),
        migrations.AlterField(
            model_name='storagebin',
            name='used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
