# Generated by Django 5.2.4 on 2025-09-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20250917_0234'),
    ]

    operations = [
        migrations.AddField(
    model_name='LocationEvent',
    name='raw_location',
    field=models.CharField(max_length=255, null=True),
),
    ]
