# Generated by Django 5.2.4 on 2025-09-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_locationevent_raw_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationevent',
            name='raw_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
