# Generated by Django 5.2.4 on 2025-09-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_locationevent_raw_location'),
        ('inventory', '0014_fix_custom_fields'),
    ]

    operations = [
    ]
