# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - newpythonkenyon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest  # Replace with your test command (e.g., python manage.py test for Django)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !__pycache__/
            !*.pyc
            !node_modules/
            !package.json
            !package-lock.json
            !.git/
            !.github/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A99DDCD1E1C143609A598656AFE2CE59 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF7F54976019464FA2EE7A62C22C2343 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F87C05E3EAB34BA4AF723CE0F925B778 }}

      - name: Delay to avoid SCM conflicts
        run: sleep 10

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'newpythonkenyon'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Optional: Use publish profile for authentication
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: 'true'  # Enable Oryx build for Python
          PYTHON_VERSION: '3.11'  # Explicitly set Python version
          WEBSITES_CONTAINER_START_TIME_LIMIT: '1800'  # Increase container startup time to 1800 seconds

      - name: Capture deployment logs
        if: failure()
        run: |
          echo "Deployment failed. Fetching logs from SCM site..."
          curl -u ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_USERNAME }}:${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PASSWORD }} https://newpythonkenyon.scm.canadacentral-01.azurewebsites.net/api/deployments/latest/log || echo "Failed to fetch logs"

      - name: Output Web App URL
        run: echo "App Service URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"